### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by kartamyshev** [behrens-de/jsDev#1]
https://github.com/behrens-de/jsDev/blob/e0a3b3954848f1f343b4ef21c70a0f060b1d49e6/randomNumber/randomNumber.js#L41

Could you please check what you are sorting here?
Seems like sorting should be done for nested array, either first one, second or both.
Otherwise these two lines don't make sense.

**Comment by behrens-de** [comment]
Thanks for your hint. I have just fixed that. That should of course mean 

if (sort === 'up') { numbs[0].sort((a, b) => a - b); } // Ascending
if (sort === 'down') { numbs[0].sort((a, b) => b - a); } // Descending

**Comment by kartamyshev** [comment]
You need to also update `runs` variable to be `loops` in return statement, there is no error since `runs` variable is undefined or undeclared (not sure is this because there is no use strict). This is a leftover after refactoring commit 🙂 .
